### DISCUSSION TITLE
استفاده از نسخه وریبل فونت

### DISCUSSION THREAD

**Discussion by asmanp2012** [rastikerdar/vazir-font#253] [Q&A]
سلام ممنون از همه تلاش هاتون برای تولید و انتشار این فونت.
من تازه با مسئله وریبل فونت ها آشنا شدم و یه مقداری گیج کننده بود برام نحوه استفاده از اون مخصوصا با فونت هایی که چندین نسخه داشتند برای همین اینجا خواستم سوالم رو بپرسم.

توی فونت وزیر ما چندین نسخه رو داریم و نسخه وریبل هم به صورت جداگانه ارائه شده
حالا من نمیتونم این نسخه های متفاوت رو از هم تفکیک کنم و نمیدونم دقیقا از کدوم نسخه باید استفاده کنم.

آیا میشه به جای لود کردن همه اون نسخه های دیگه نسخه وریبل رو لود کرد توی صفحه html ؟
 و آیا در مرورگر های قدیمی تر که نسخه وریبل رو ساپورت نمیکنن از کدوم فایل باید استفاده کرد؟ 
آیا برای مروگر های قدیمی همه فایل ها رو باید لود کنم؟ 

همین مشکل رو با فونت ساحل هم دارم.

**Comment by rastikerdar** [comment]
## Update
یک صفحه راهنما برای نسخه متغیر ایجاد شد
https://rastikerdar.github.io/vazirmatn/fa/docs/Vazirmatn-Variable-fa

## توضیح
سلام
می‌تونید به جای نسخه تمام ارقام فارسی از همان نسخه اصلی ثابت یا وریبل (فرقی نمی‌کنه) به همراه "ss01" استفاده کنید. در صفحه زید ss01 رو جستجو کنید.
https://rastikerdar.github.io/vazirmatn/fa/docs/HELP-fa
 همچنین به جای همه وزن‌ها از فایل وریبل استفاده کنید. آن نسخه‌ها کاربرد خودشون رو دارند و وریبل وزیرمتن جای همه رو نمی‌گیره. مانند نسخه «بدون لاتین» یا نسخه «UI» و ... درواقع مهمترین مزیت وریبل وزیرمتن، ترکیب همه وزن‌ها (۹ تا) در یک فایل کم حجم هست.
پشتیبانی مرورگرها رو می‌تونید از اینجا بررسی کنید:
https://caniuse.com/variable-fonts
برای مرورگرهای قدیمی از نسخه‌های ثابت که هر وزن در یک فایل جدا قرار داره استفاده کنید.

نحوه استفاده از وریبل در وب ساده هست:
```css
@font-face {
  font-family: Vazirmatn;
  src: url('fonts/webfonts/Vazirmatn[wght].woff2') format('woff2');
  font-weight: 400;
  font-style: normal;
  font-display: swap;
}

body {
    font-family: Vazirmatn;
    font-variation-settings: "wght" 400;
}

h1 {
    font-variation-settings: "wght" 900;
}
```
جای 900 هر عددی از 100 تا 900 می‌تونید بذارید.
(باید یه صفحه راهنما برایش بنویسم)
