### ISSUE TITLE
ترکیب فونت با open sans

### ISSUE THREAD

**Issue by aliajoudanian** [rastikerdar/vazir-font#56]
اگر بخواهیم فونت وزیر را با فونت اوپن سنس ترکیب کنیم راهی بهتر از استفاده از نرم افزار 
Font Forge
وجود داره؟

**Comment by rastikerdar** [comment]
در حال حاضر خیر. کار ساده ایست و فقط هم یک بار کافیست انجامش دهید. اگر مشکلی داشتید بفرمایید خودم برایتان انجام می‌دهم.

**Comment by aliajoudanian** [comment]
@rastikerdar ممنون از شما.
اینکه میفرمائید فقط هم یک بار کافیه انجام داد یعنی در آپدیت‌های بعدی فونتتون هم ریپلیس کردن کار خاصی نداره؟

**Comment by rastikerdar** [comment]
برای هر بار آپدیت باید ترکیب بشه. راستش اصلا راهی به ذهنم نمی‌رسه
:(
آپدیت‌ها تا الان بیشتر به خاطر تغییرات جزئی در طراحی هست. فرآیند طراحی متوقف بشه دیگه آپدیتی نمیاد.

**Comment by ma-sadeghi** [comment]
@rastikerdar با سلام. ببخشید هرکدوم از این فونتها چندین فایل داره مثلا بولد، رگولار،  و غیره. برای ترکیب همه اینها چه باید کرد؟

**Comment by ma-sadeghi** [comment]
من موفق شدم OpenSans رو با Vazirmatn ترکیب کنم (همونطور که آقای @rastikerdar گفتند کار سختی نبود). در مورد نحوه ترکیب italic و regular یک بار Vazirmatn رو با نسخه OpenSans Regular ترکیب کردم و یکبار با italic. برای سهولت استفاده، این دو فایل رو به فرمت woff2 خروجی گرفتم و در گیتهاب گذاشتم. صرفا اگر کسی خواست استفاده کنه این چند خط رو به فایل CSS پروژه میتونه اضافه کنه و از فونت ترکیبی VazirmatnOpenSansMashup استفاده کنه.

```css
@font-face {
    font-family: 'VazirmatnOpenSansMashup';
    src: url('https://raw.githubusercontent.com/ma-sadeghi/assets/main/fonts/VazirmatnOpenSansMashup-Regular.woff2') format('woff2');
    font-weight: normal;
    font-style: normal;
}

@font-face {
    font-family: 'VazirmatnOpenSansMashup';
    src: url('https://raw.githubusercontent.com/ma-sadeghi/assets/main/fonts/VazirmatnOpenSansMashup-Italic.woff2') format('woff2');
    font-weight: normal;
    font-style: italic;
}
```

cc: @aliajoudanian
